### ISSUE TITLE
Error on importing Package

### ISSUE THREAD

**Issue by jandornhege** [basti564/augaudio#2]
`>>> import augaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python37\lib\site-packages\augaudio\__init__.py", line 1, in <module>
    import librosa as lr
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\util\utils.py", line 15, in <module>
    from .decorators import deprecated
  File "C:\Users\Jan\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\util\decorators.py", line 9, in <module>
    from numba.decorators import jit as optional_jit
ModuleNotFoundError: No module named 'numba.decorators'`

**Comment by ptrpaws** [comment]
https://github.com/librosa/librosa/issues/1160#issuecomment-643068317
```pip install numba==0.48``` should fix this issue
